export function id(prefix: string): string {
  return `${prefix}_${Math.random().toString(36).slice(2, 10)}${Date.now().toString(36).slice(-4)}`;
}

export const IDS = {
  company: "ent_atlas",
  contact: "ent_amine",
  opportunity: "ent_opp_320k",
  document: "ent_proposal_v2",
  message1: "evt_msg_proposal",
  message2: "evt_msg_discount",
  evtDealCreated: "evt_deal_320k",
  evtCommitOursCreated: "evt_cmt_ours_created",
  evtCommitTheirsCreated: "evt_cmt_theirs_created",
  evtCommitMissed: "evt_cmt_ours_missed",
  evtClockSkip: "evt_clock_skip",
  evtCustomerReplied: "evt_msg_discount_reply",
  evtPolicyBlocked: "evt_policy_discount_10",
  commitOurs: "cmt_send_proposal",
  commitTheirs: "cmt_decision_friday",
  commitSign: "cmt_sign_today",
  expectOurs: "exp_send_proposal",
  expectTheirs: "exp_decision_friday",
  expectSign: "exp_sign_today",
  depDecisionOnProposal: "dep_decision_on_proposal",
  excMissed: "exc_proposal_missed",
  excDiscount: "exc_discount_blocked",
  planRecovery: "pln_recovery_320k",
  planDiscount: "pln_discount_alt",
  actPrepare: "act_prepare_proposal",
  actDraft: "act_draft_followup",
  actCheck: "act_checkpoint",
  actDiscount: "act_apply_10",
  actAlt5: "act_offer_5",
  actAltTerms: "act_offer_terms",
  actAltDraft: "act_draft_policy_reply",
  goalRevenue: "gol_month_revenue",
  supplier: "ent_atlas_supply",
  shipment: "ent_ship_204",
  product: "ent_product_rk7",
  orderA: "ent_order_a",
  orderB: "ent_order_b",
  orderC: "ent_order_c",
  customerA: "ent_cust_a",
  customerB: "ent_cust_b",
  customerC: "ent_cust_c",
  invoiceA: "ent_inv_a",
  invoiceB: "ent_inv_b",
  invoiceC: "ent_inv_c",
  cashWeek: "ent_cash_week",
  commitShip: "cmt_ship_monday",
  commitDeliverA: "cmt_deliver_order_a",
  expectShip: "exp_ship_monday",
  expectDeliverA: "exp_deliver_order_a",
  excDelay: "exc_shipment_delay",
  evtShipExpected: "evt_ship_expected",
  evtSupplierMsg: "evt_msg_supplier_delay",
  evtShipDelayed: "evt_ship_delayed",
  evtExceptionDelay: "evt_exc_delivery_delay",
  evtCascade: "evt_cascade_detected",
  evtOrderA: "evt_order_a_affected",
  evtOrderB: "evt_order_b_affected",
  evtOrderC: "evt_order_c_affected",
  evtExceptionMiss: "evt_exc_proposal_missed",
} as const;
